# Generated by Django 5.2.17 on 2026-09-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电站名称')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='电站编码')),
                ('city', models.CharField(max_length=100, verbose_name='所在地区')),
                ('capacity_kwp', models.FloatField(verbose_name='装机容量(kWp)')),
                ('status', models.CharField(choices=[('running', '运行正常'), ('maintenance', '检修中'), ('fault', '故障')], default='running', max_length=20, verbose_name='运行状态')),
                ('grid_date', models.DateField(blank=True, null=True, verbose_name='并网日期')),
                ('owner', models.CharField(blank=True, default='', max_length=100, verbose_name='业主单位')),
                ('contact', models.CharField(blank=True, default='', max_length=30, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '电站',
                'verbose_name_plural': '电站',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=120, verbose_name='工单标题')),
                ('order_type', models.CharField(choices=[('regular', '定期巡检'), ('special', '专项巡检'), ('fault', '故障巡检')], default='regular', max_length=20, verbose_name='巡检类型')),
                ('assignee', models.CharField(max_length=30, verbose_name='执行人')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('done', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result', models.TextField(blank=True, default='', verbose_name='巡检结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.station', verbose_name='电站')),
            ],
            options={
                'verbose_name': '巡检工单',
                'verbose_name_plural': '巡检工单',
                'ordering': ['-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('inverter', '逆变器'), ('combiner', '汇流箱'), ('transformer', '箱式变压器'), ('meter', '电能表'), ('monitor', '环境监测仪')], max_length=20, verbose_name='设备类型')),
                ('model', models.CharField(blank=True, default='', max_length=60, verbose_name='型号')),
                ('serial_no', models.CharField(blank=True, default='', max_length=60, verbose_name='序列号')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '告警'), ('fault', '故障'), ('offline', '离线')], default='normal', max_length=20, verbose_name='状态')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.station', verbose_name='所属电站')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DefectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='缺陷编号')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('level', models.CharField(choices=[('minor', '一般'), ('major', '严重'), ('critical', '危急')], default='minor', max_length=20, verbose_name='缺陷级别')),
                ('status', models.CharField(choices=[('open', '待消缺'), ('processing', '消缺中'), ('resolved', '已消缺')], default='open', max_length=20, verbose_name='状态')),
                ('reporter', models.CharField(max_length=30, verbose_name='发现人')),
                ('handler', models.CharField(blank=True, default='', max_length=30, verbose_name='消缺人')),
                ('found_at', models.DateField(verbose_name='发现日期')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='消缺时间')),
                ('solution', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='core.device', verbose_name='关联设备')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.station', verbose_name='电站')),
            ],
            options={
                'verbose_name': '消缺记录',
                'verbose_name_plural': '消缺记录',
                'ordering': ['-found_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CleaningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='计划编号')),
                ('area', models.CharField(max_length=100, verbose_name='清洗区域')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('executor', models.CharField(max_length=50, verbose_name='执行人/班组')),
                ('status', models.CharField(choices=[('planned', '待执行'), ('in_progress', '进行中'), ('done', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='core.station', verbose_name='电站')),
            ],
            options={
                'verbose_name': '清洗计划',
                'verbose_name_plural': '清洗计划',
                'ordering': ['-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '提示'), ('minor', '一般'), ('major', '严重'), ('critical', '紧急')], default='minor', max_length=20, verbose_name='告警级别')),
                ('title', models.CharField(max_length=120, verbose_name='告警标题')),
                ('message', models.TextField(blank=True, default='', verbose_name='告警详情')),
                ('status', models.CharField(choices=[('open', '未处理'), ('processing', '处理中'), ('resolved', '已处理')], default='open', max_length=20, verbose_name='处理状态')),
                ('handler', models.CharField(blank=True, default='', max_length=30, verbose_name='处理人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='core.device', verbose_name='关联设备')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.station', verbose_name='电站')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('energy_kwh', models.FloatField(verbose_name='发电量(kWh)')),
                ('peak_power_kw', models.FloatField(default=0, verbose_name='峰值功率(kW)')),
                ('equivalent_hours', models.FloatField(default=0, verbose_name='等效利用小时(h)')),
                ('pr', models.FloatField(default=0, verbose_name='系统效率PR(%)')),
                ('irradiance', models.FloatField(default=0, verbose_name='水平面辐照量(kWh/m²)')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_data', to='core.station', verbose_name='电站')),
            ],
            options={
                'verbose_name': '发电数据',
                'verbose_name_plural': '发电数据',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['station', 'date'], name='core_powerd_station_ebf3df_idx')],
                'unique_together': {('station', 'date')},
            },
        ),
    ]
