# Generated by Django 5.2.17 on 2026-09-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='handle_note',
            field=models.TextField(blank=True, default='', verbose_name='处置措施'),
        ),
        migrations.AddField(
            model_name='defectrecord',
            name='source_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_defects', to='core.alarm', verbose_name='来源告警'),
        ),
        migrations.AddField(
            model_name='inspectionorder',
            name='source_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_inspections', to='core.alarm', verbose_name='来源告警'),
        ),
        migrations.AlterField(
            model_name='defectrecord',
            name='status',
            field=models.CharField(choices=[('open', '待消缺'), ('processing', '消缺中'), ('resolved', '已消缺'), ('cancelled', '已作废')], default='open', max_length=20, verbose_name='状态'),
        ),
    ]
